[tool.poetry]
name = "django-backblaze-b2"
version = "0.1.0"
description = ""
authors = ["Étienne H <et@hossack.me>"]

[tool.poetry.dependencies]
python = "^3.8"
b2sdk = "^1.1.4"
django = ">=3.0"

[tool.poetry.dev-dependencies]
isort = "^5.4.2"
pytest = "^5.2"
mypy = "^0.782"
black = "^19.10b0"
django-stubs = {git = "https://github.com/typeddjango/django-stubs.git", rev = "95252cde60239b7f3eb5a38973e313b51de15335"}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
