version: 2.1

orbs:
  python: circleci/python@1.2.1

jobs:
  build-and-test:
    machine: true
    steps:
      - checkout
      - run:
          command: make test-ci
          name: Run tests, lint
      - store_test_results:
          path: tests/test-results
      - store_artifacts:
          path: tests/htmlcov

workflows:
  main:
    jobs:
      - build-and-test
